services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./my_policy.xml:/etc/ImageMagick-6/policy.xml 
