services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./my_policy.xml:/etc/ImageMagick-6/policy.xml
    networks:
      - back 
  web:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    networks:
      - back

networks:
  back:

